import type { Metadata } from "next";
import { Onest, Manrope } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import ConditionalNavbar from "./components/ConditionalNavbar";
import { Toaster } from "react-hot-toast";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Loan Aid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.className} ${manrope.className} antialiased`}>
        <ConditionalNavbar />
        <Toaster />
        {children}
        <Footer />
      </body>
    </html>
  );
}
